const USER_ADDED = 'USER_ADDED';
const MEETUP_ADDED = 'MEETUP_ADDED';
const VOTE_ADDED = 'VOTE_ADDED';
const VOTES_CLEARED = 'VOTES_CLEARED';

module.exports = {
    USER_ADDED,
    MEETUP_ADDED,
    VOTE_ADDED,
    VOTES_CLEARED
}